// 중앙 도서관의 유령 사서
// Generated by Mystery VN Pipeline (Kamaitachi Style)
// 2026-02-01T11:43:49.157Z

'use strict';

// ========================================
// Storage 초기화 (플래그 시스템)
// ========================================
monogatari.storage({
  "clue_count": 0,
  "st_correct_culprit": false,
  "st_correct_trick": false,
  "st_correct_motive": false,
  "st_wrong_accusation": false,
  "ev_call_slip": false,
  "ev_power_log": false,
  "ev_glue_smell": false,
  "ev_perfect_book": false,
  "ev_scuff_marks": false,
  "ts_yoon_alibi": false,
  "ts_park_alibi": false,
  "ts_choi_witness": false,
  "ts_choi_ghost": false,
  "vs_rotunda": false,
  "vs_security_room": false,
  "st_found_victim_missing": false
});

// ========================================
// 캐릭터 정의
// ========================================
monogatari.characters({
  "char_protagonist": {
    "name": "김민준",
    "color": "#4a90e2"
  },
  "char_victim": {
    "name": "오진혁",
    "color": "#888888"
  },
  "char_suspect1": {
    "name": "박지수",
    "color": "#9013fe"
  },
  "char_suspect2": {
    "name": "김태준",
    "color": "#d0021b"
  },
  "char_suspect3": {
    "name": "최민아",
    "color": "#f5a623"
  },
  "char_culprit": {
    "name": "윤필서",
    "color": "#5f4b32"
  }
});

// ========================================
// 배경 정의
// ========================================
monogatari.assets('scenes', {
  "bg_rotunda": "#4a4a4a",
  "bg_security_room": "#1e3a5f",
  "bg_archives_900": "#5d4a3a",
  "bg_archives_400": "#6b5b95",
  "bg_lounge": "#86ac41",
  "bg_archives_special": "#3e5641",
  "bg_underground_workshop": "#2a2a2a",
  "bg_library_entrance": "#c0c0c0"
});

// ========================================
// 스크립트
// ========================================
monogatari.script({
  'scene_prologue_01': [
    'show scene bg_library_entrance',
    '웅장한 중앙 도서관. 나의 논문 주제인 \'거대 회전 서가의 건축 역학\'에 대해 조사하기 위해, 나는 폐관 시간 이후에도 남을 수 있도록 특별 허가를 받았다.',
    'char_victim 김민준 학생, 다시 말하지만 폐관 후에는 절대 지정된 구역을 벗어나면 안 되네. 특히 중앙 로툰다는 위험하니 함부로 조작하지 말게.',
    'char_protagonist 네, 사서장님. 명심하겠습니다. 배려해주셔서 감사합니다.',
    '원리원칙을 중시하는 오진혁 사서장. 그의 완고한 표정 뒤로 무언가에 대한 강한 호기심이 스치는 것을 나는 놓치지 않았다.',
    'jump scene_prologue_02',
  ],
  'scene_prologue_02': [
    'show scene bg_rotunda',
    '얼마 후, 로툰다 근처에서 언성이 높아지는 소리가 들렸다.',
    'char_suspect2 이봐, 사서장! 내 컬렉션에 꼭 필요한 책이란 말이야! 열람만이라도 하게 해줘!',
    'char_victim 김태준 씨, 규정은 규정입니다. 보존 상태가 좋지 않아 특별 허가 없이는 절대 불가합니다.',
    '고서 수집가 김태준이 씩씩거리며 자리를 떴다. 그 뒤를 이어 수석 사서 박지수가 다가왔다.',
    'char_suspect1 사서장님, 해외 도서관과의 협력 건, 재검토가 필요해 보입니다. 지금 방식은 너무 비효율적이에요.',
    'char_victim 박 사서, 내 방식에 불만 있나? 아직은 내가 책임자일세.',
    '두 사람 사이에는 차가운 기류가 흘렀다. 저편에서는 기록물 관리사 최민아가 잔뜩 주눅이 든 채 서류를 옮기고 있었고, 나이 든 사서 한 분이 묵묵히 책을 정리하고 있었다.',
    'jump scene_prologue_03',
  ],
  'scene_prologue_03': [
    'show scene bg_rotunda',
    '시간은 흘러 밤 10시가 가까워졌다. 나는 2층 열람실에서 자료를 정리하고 있었다.',
    '그때였다.',
    'jump scene_incident_01',
  ],
  'scene_incident_01': [
    'show scene bg_rotunda',
    '끼이이이이익-! 귀를 찢는 듯한 경보음이 도서관 전체에 울려 퍼졌다.',
    '동시에 철컹, 하는 소리와 함께 모든 출입문이 폐쇄되었다.',
    'char_protagonist 이, 이게 무슨 소리지?',
    '나는 급히 중앙 로툰다로 향했다. 그곳에는 나처럼 놀란 얼굴의 사람들이 모여들고 있었다.',
    'jump scene_incident_02',
  ],
  'scene_incident_02': [
    'show scene bg_rotunda',
    function() {
          const flags = JSON.parse('{\"st_found_victim_missing\":true}');
          const s = monogatari.storage();
          for (const [k, v] of Object.entries(flags)) {
            s[k] = v;
          }
          monogatari.storage(s);
        },
    'char_suspect1 고서 도난 경보예요! 모두 침착하세요! 일단 사서장님부터...',
    'char_suspect3 사, 사서장님이... 안 보이세요!',
    'char_suspect2 뭐? 그 영감탱이가 어디 갔어!',
    'char_culprit 이런... 큰일이군요...',
    '모두가 당황한 사이, 나는 로툰다 중앙 바닥에서 무언가 이상한 점을 발견했다. 오진혁 사서장은... 마치 연기처럼 사라져 버렸다.',
    'jump scene_investigation_hub',
  ],
  'scene_investigation_hub': [
    'show scene bg_rotunda',
    '경찰이 도착하려면 시간이 걸린다. 그 전에 내가 직접 단서를 찾아봐야 한다.',
    'char_protagonist (어디부터 조사해볼까?)',
    {
      'Choice': {
        'opt_jfdsr': {\n          'Text': '사건 현장, 중앙 로툰다를 조사한다.',\n          'Condition': (function() { return monogatari.storage().vs_rotunda !== true; }),\n          'Do': 'jump scene_investigation_rotunda'\n        },\n        'opt_edvdq': {\n          'Text': '보안 시스템을 확인하러 보안실로 간다.',\n          'Condition': (function() { return monogatari.storage().vs_security_room !== true; }),\n          'Do': 'jump scene_investigation_security'\n        },\n        'opt_qtlsi': {\n          'Text': '900번대 역사 서고를 조사한다.',\n          'Do': 'jump scene_investigation_archives900'\n        },\n        'opt_b6naa': {\n          'Text': '400번대 어학 서고를 조사한다.',\n          'Do': 'jump scene_investigation_archives400'\n        },\n        'opt_qqf8g': {\n          'Text': '직원 휴게실에서 이야기를 들어본다.',\n          'Do': 'jump scene_investigation_lounge'\n        },\n        'opt_k3hgu': {\n          'Text': '특별 자료실을 확인해본다.',\n          'Do': 'jump scene_investigation_special_archives'\n        },\n        'opt_g2f2c': {\n          'Text': '수사를 마치고 추리를 시작한다.',\n          'Condition': (function() { return (monogatari.storage().clue_count || 0) >= 3; }),\n          'Do': 'jump scene_investigation_end'\n        }\n      }
    },
  ],
  'scene_investigation_rotunda': [
    'show scene bg_rotunda',
    function() {
          const flags = JSON.parse('{\"vs_rotunda\":true}');
          const s = monogatari.storage();
          for (const [k, v] of Object.entries(flags)) {
            s[k] = v;
          }
          monogatari.storage(s);
        },
    '사서장이 사라진 로툰다. 거대한 원형 서가는 불길한 침묵을 지키고 있다.',
    '나는 바닥을 살피다가 희미하게 무언가에 쓸린 자국을 발견했다. 누군가를 급하게 옮긴 흔적 같다. [단서: 바닥의 끌린 자국 획득]',
    '그리고 중앙 제어 콘솔 옆에 작은 종이 한 장이 떨어져 있었다. 대출 신청서 같지만, 적힌 청구기호가 이상하다. \'027.4-L847-v.2\'... [단서: 이상한 청구기호가 적힌 대출 신청서 획득]',
    'char_protagonist (이 숫자들이 의미하는 건 뭘까? 단순한 책 번호는 아닌 것 같은데...)',
    'jump scene_investigation_hub',
  ],
  'scene_investigation_security': [
    'show scene bg_security_room',
    function() {
          const flags = JSON.parse('{\"vs_security_room\":true}');
          const s = monogatari.storage();
          for (const [k, v] of Object.entries(flags)) {
            s[k] = v;
          }
          monogatari.storage(s);
        },
    '보안실에는 수석 사서 박지수가 신경질적으로 모니터를 보고 있었다.',
    'char_suspect1 흥, 내가 범인이라고 의심하는 건가요? 21시 30분부터 경보가 울릴 때까지 시드니 도서관이랑 화상 회의 중이었어요. 서버 기록 확인해보시죠. [증언: 박지수의 증언 획득]',
    'char_protagonist 알겠습니다. 혹시 시스템에 이상한 점은 없었나요?',
    'char_suspect1 글쎄요... 아, 전력 사용 기록이 좀 이상하긴 하네요. 경보가 울린 22시 정각에 로툰다 구역에서 엄청난 전력 스파크가 있었어요. 단순 회전과는 비교도 안 될 정도로.',
    '나는 그녀가 가리키는 모니터를 확인했다. 그래프가 비정상적으로 치솟아 있었다. [단서: 도서관 전력 사용 기록 획득]',
    'jump scene_investigation_hub',
  ],
  'scene_investigation_archives900': [
    'show scene bg_archives_900',
    '900번대 역사 서고. 낡은 책 냄새가 가득한 곳이다. 그곳에서 조용히 책을 정리하던 노신사, 윤필서 씨를 만났다.',
    'char_protagonist 선생님, 경보가 울렸을 때 어디에 계셨습니까?',
    'char_culprit 저는 그 시간에... 저쪽 900번대 서가에서 먼지 쌓인 역사책들을 정리하고 있었습니다. 갑자기 경보가 울려서 깜짝 놀랐지요. [증언: 윤필서의 증언 획득]',
    '그와 대화하던 중, 나는 특정 환풍구 근처에서 이상한 냄새를 맡았다. 낡은 종이 냄새에 섞인, 독특하고 시큼한 아교풀 냄새였다. [단서: 900번대 서고의 낯선 냄새 획득]',
    'char_culprit 글쎄요... 워낙 오래된 책들이 많아서 별별 냄새가 다 난답니다. 허허...',
    'jump scene_investigation_hub',
  ],
  'scene_investigation_archives400': [
    'show scene bg_archives_400',
    '400번대 어학 서고에는 고서 수집가 김태준이 불만 가득한 얼굴로 서성이고 있었다.',
    'char_suspect2 뭘 봐? 내가 그 영감탱이를 어떻게 했다고 의심하는 거냐? 난 그냥 책 좀 보려던 것뿐이야!',
    '그때, 최민아 씨가 겁먹은 얼굴로 다가왔다.',
    'char_suspect3 저... 경보가 울리기 직전에... 김태준 씨가 400번대 서고 문을 막 흔들면서 열려고 하는 걸 봤어요... 너무 무서웠어요. [증언: 최민아의 목격담 획득]',
    'char_suspect2 시끄러! 잠긴 문 좀 열어보려던 게 뭐 어쨌다고!',
    '김태준은 버럭 소리를 지르며 자리를 피했다. 그의 알리바이는 확실해 보이지만, 무언가를 숨기는 듯한 태도가 마음에 걸린다.',
    'jump scene_investigation_hub',
  ],
  'scene_investigation_lounge': [
    'show scene bg_lounge',
    '직원 휴게실 구석에서 최민아 씨가 혼자 떨고 있었다.',
    'char_protagonist 최민아 씨, 괜찮으세요? 혹시 짚이는 점이라도 있나요?',
    'char_suspect3 저... 이건 그냥 소문인데요... 이 도서관에는 \'유령 사서\'가 살고 있대요...',
    'char_protagonist 유령 사서요?',
    'char_suspect3 네... 낡고 찢어진 책이 다음날 보면... 새것처럼 깨끗하게 고쳐져 있곤 했어요. 사서장님도 그걸 이상하게 여기고 혼자서 뭔가를 계속 조사하고 계셨던 것 같아요... [증언: 최민아의 소문 이야기 획득]',
    '그녀의 이야기는 황당했지만, 사서장의 최근 행적과 관련된 중요한 단서처럼 느껴졌다.',
    'jump scene_investigation_hub',
  ],
  'scene_investigation_special_archives': [
    'show scene bg_archives_special',
    '최민아의 이야기가 마음에 걸려 특별 자료실을 확인해보기로 했다.',
    '사서장의 연구 기록을 살펴보던 중, \'유령 사서\'에 대한 메모와 함께 특정 고서의 관리 번호가 적혀 있었다.',
    '해당 서가로 가 책을 꺼내 본 나는 놀라지 않을 수 없었다. 분명 10년 전 기록에는 심하게 훼손되어 폐기 직전이라고 되어 있는데, 내 손에 들린 책은 마치 어제 인쇄한 것처럼 완벽했다. [단서: 완벽하게 복원된 고서 획득]',
    'char_protagonist (이건... 인간의 솜씨라고 믿기 어려울 정도의 복원 기술이야. \'유령 사서\'는 실존하는 걸까?)',
    'jump scene_investigation_hub',
  ],
  'scene_investigation_end': [
    'show scene bg_rotunda',
    '나는 모은 단서들을 머릿속으로 정리했다.',
    (function() {
          const result = (monogatari.storage().clue_count || 0) >= 5;
          if (result) {
            return '충분한 단서를 모았다. 사건의 전말이 보이기 시작한다.';
          } else {
            return '아직 단서가 부족한 느낌이지만... 더 이상 시간을 지체할 수는 없다.';
          }
        }),
    'char_protagonist 여러분, 잠시 주목해주시겠습니까? 사서장님의 실종에 대해 제가 알아낸 것들을 말씀드리겠습니다.',
    'jump scene_deduction_start',
  ],
  'scene_deduction_start': [
    'show scene #2d2d44',
    '이제 범인을 지목할 시간이다...',
    'jump _deduction_q_culprit',
  ],
  'scene_ending_true_01': [
    'show scene bg_rotunda',
    '당신의 완벽한 추리에 따라, 모든 진실이 밝혀졌다.',
    'char_protagonist 사서장님은 이 도서관 어딘가에 살아계십니다. 그리고 범인은... 사서장님을 사라지게 하기 위해 이 로툰다의 숨겨진 기능을 이용했습니다.',
    'char_protagonist 경보가 울렸을 때 발생한 거대한 전력 스파크. 그건 이 로툰다가 단순한 회전 서가가 아니라, 아래로 내려가는 거대한 엘리베이터라는 증거입니다!',
    '나는 로툰다 콘솔에 다가가, 현장에서 발견한 종이에 적힌 청구기호 \'027.4-L847-v.2\'를 입력했다.',
    'jump scene_ending_true_02',
  ],
  'scene_ending_true_02': [
    'show scene bg_underground_workshop',
    '묵직한 기계음과 함께, 발밑의 거대한 서가가 통째로 하강하기 시작했다. 모두가 경악하는 가운데, 우리는 어둡고 오래된 공간으로 내려갔다.',
    '그곳은 수많은 책과 전문적인 복원 도구로 가득 찬 비밀 작업실이었다. 그리고 그 중앙에는... 의자에 묶여 있지만 멀쩡한 모습의 오진혁 사서장과, 그의 곁을 지키고 선 윤필서 씨가 있었다.',
    'char_culprit ......결국 찾아내셨군요.',
    'jump scene_ending_true_03',
  ],
  'scene_ending_true_03': [
    'show scene bg_underground_workshop',
    '윤필서 씨는 20년 전, 폐기될 책들을 살리기 위해 스스로 죽음을 위장하고 이 지하에 숨어들어와 책을 복원하며 살아온 \'유령 사서\'였다.',
    '자신의 존재를 눈치챈 사서장이 이곳을 찾아내자, 그는 자신의 삶과 책들을 지키기 위해 사서장을 잠시 감금했던 것이다.',
    'char_victim 허허... 이보게 윤 선배, 내가 이길 줄 알았는데... 자네의 책에 대한 열정은 도저히 못 당하겠군.',
    '그의 황당하지만 숭고한 사연에 모두가 말을 잃었다. 사건은 해프닝으로 마무리되었고, 중앙 도서관은 새로운 비밀과 함께 내일을 맞이하게 되었다.',
  ],
  'scene_ending_good_01': [
    'show scene bg_rotunda',
    '당신은 범인과 그가 사용한 트릭을 정확히 간파했다.',
    'char_protagonist 로툰다는 아래로 내려가는 엘리베이터입니다! 윤필서 씨, 당신이 사서장님을 데리고 지하로 내려간 거죠!',
    '당신의 추리에 따라 로툰다를 작동시키자, 지하의 비밀 공간이 드러났다. 그곳에서 오진혁 사서장이 무사히 발견되었다.',
    'char_culprit ......',
    '하지만 당신은 그가 왜 이런 일을 벌였는지, 그의 진짜 동기까지는 이해하지 못했다.',
    'char_suspect1 책에 미쳐서 사서장님을 납치 감금하다니... 제정신이 아니군요. 당장 경찰에 넘기죠.',
    '윤필서는 그저 책에 미친 노인 취급을 받으며 연행되었다. 도서관의 비밀은 일부만 밝혀진 채, 씁쓸하게 사건이 종결되었다.',
  ],
  'scene_ending_normal_01': [
    'show scene bg_rotunda',
    '당신은 여러 정황 증거를 통해 범인으로 윤필서를 정확히 지목했다.',
    'char_protagonist 윤필서 씨, 900번대 서고의 이상한 냄새... 당신과 관련이 있죠? 사서장님은 어디에 계십니까!',
    '하지만 그가 사용한 기상천외한 트릭까지는 밝혀내지 못했다. 당신의 계속된 추궁에 압박감을 느낀 윤필서는 결국 스스로 입을 열었다.',
    'char_culprit ...사서장님은... 무사하십니다. 저를 따라오시지요.',
    '그는 900번대 서고의 환풍구 뒤에 숨겨진 비밀 통로를 열었다. 결국 사서장은 무사히 구출되었다.',
    '그러나 로툰다의 거대한 비밀은 영원히 책장 속에 묻히고 말았다. 당신은 사건을 해결했지만, 진실의 전모에는 다다르지 못했다.',
  ],
  'scene_ending_bad_01': [
    'show scene bg_rotunda',
    '당신이 지목한 사람은 범인이 아니었다.',
    'char_suspect1 지금 제정신이세요? 말도 안 되는 소리 하지 마세요!',
    'char_suspect2 어이, 학생. 추리 소설을 너무 많이 읽은 거 아니야?',
    '당신의 섣부른 추리는 모두의 비웃음만 산 채, 아무런 해결도 이끌어내지 못했다.',
    '진범을 찾지 못한 채 시간은 흘러갔고, 결국 경찰이 도착해 수사를 인계받았다. 하지만 결정적인 증거는 나오지 않았다.',
    '오진혁 사서장 실종 사건은 영구 미제로 남았고, 도서관의 어딘가에서는 오늘도 유령 사서가 조용히 책장을 넘기고 있을 것이다.',
  ],
  '_deduction_q_culprit_wrong': [
    '아닙니다. 다른 용의자에게는 확실한 알리바이가 있거나 동기가 부족합니다. 다시 생각해보죠.',
    'jump _deduction_q_trick',
  ],
  '_deduction_q_culprit_correct': [
    '맞습니다. 조용히 책을 정리하던 노신사 윤필서, 그가 바로 이 사건의 범인입니다.',
    (function() {
          const s = monogatari.storage();
          s['st_correct_culprit'] = true;
          monogatari.storage(s);
        }),
    'jump _deduction_q_trick',
  ],
  '_deduction_q_culprit': [
    '"사서장 오진혁을 사라지게 한 인물은 누구인가?"',
    {
      'Choice': {
        'q_opt_itmpl': {\n          'Text': '박지수',\n          'Do': 'jump _deduction_q_culprit_wrong'\n        },\n        'q_opt_i0dsn': {\n          'Text': '김태준',\n          'Do': 'jump _deduction_q_culprit_wrong'\n        },\n        'q_opt_kbz8o': {\n          'Text': '최민아',\n          'Do': 'jump _deduction_q_culprit_wrong'\n        },\n        'q_opt_v6cp4': {\n          'Text': '윤필서',\n          'Do': 'jump _deduction_q_culprit_correct'\n        }\n      }
    },
  ],
  '_deduction_q_trick_wrong': [
    '그 방법으로는 이 거대한 도서관에서 사람 한 명을 완벽하게 숨길 수 없습니다.',
    'jump _deduction_q_motive',
  ],
  '_deduction_q_trick_correct': [
    '정확합니다. 로툰다의 비정상적인 전력 사용 기록과 이상한 청구기호가 적힌 쪽지가 바로 그 증거입니다.',
    (function() {
          const s = monogatari.storage();
          s['st_correct_trick'] = true;
          monogatari.storage(s);
        }),
    'jump _deduction_q_motive',
  ],
  '_deduction_q_trick': [
    '"범인은 어떻게 사서장을 모두의 눈을 피해 감쪽같이 숨겼는가?"',
    {
      'Choice': {
        'q_opt_bw9pm': {\n          'Text': '아무도 안보는 사이에 사서장을 업고 다른 방으로 도망쳤다.',\n          'Do': 'jump _deduction_q_trick_wrong'\n        },\n        'q_opt_emvkx': {\n          'Text': '원형 서가(로툰다)를 암호(청구기호)로 작동시켜 지하로 피해자를 숨기고, 비밀 통로로 알리바이를 만들었다.',\n          'Do': 'jump _deduction_q_trick_correct'\n        },\n        'q_opt_f3u9m': {\n          'Text': '사서장을 책장 뒤 좁은 공간에 숨겨두었다.',\n          'Do': 'jump _deduction_q_trick_wrong'\n        },\n        'q_opt_o27cv': {\n          'Text': '다른 용의자들과 공모하여 사서장을 숨겼다.',\n          'Do': 'jump _deduction_q_trick_wrong'\n        }\n      }
    },
  ],
  '_deduction_q_motive_wrong': [
    '그 동기는 다른 용의자에게 더 어울리는 것입니다. 범인의 행동을 다시 떠올려보세요.',
    'jump _deduction_complete',
  ],
  '_deduction_q_motive_correct': [
    '그렇습니다. 그는 \'유령 사서\'로서의 자신의 삶을 지키고 싶었던 겁니다. 사서장을 해칠 의도는 없었습니다.',
    (function() {
          const s = monogatari.storage();
          s['st_correct_motive'] = true;
          monogatari.storage(s);
        }),
    'jump _deduction_complete',
  ],
  '_deduction_q_motive': [
    '"범인의 진짜 목적은 무엇이었는가?"',
    {
      'Choice': {
        'q_opt_m2pr4': {\n          'Text': '사서장 자리를 차지하기 위해.',\n          'Do': 'jump _deduction_q_motive_wrong'\n        },\n        'q_opt_x491x': {\n          'Text': '자신이 도서관 지하에 숨어 산다는 사실과 책을 복원해온 평생의 업적을 숨기기 위해.',\n          'Do': 'jump _deduction_q_motive_correct'\n        },\n        'q_opt_wq7r5': {\n          'Text': '개인적인 원한으로 복수하기 위해.',\n          'Do': 'jump _deduction_q_motive_wrong'\n        },\n        'q_opt_l69ny': {\n          'Text': '귀중한 고서를 훔치기 위해.',\n          'Do': 'jump _deduction_q_motive_wrong'\n        }\n      }
    },
  ],
  '_deduction_complete': [
    '추리가 끝났다...',
    (function() {
    const s = monogatari.storage();
    
    if (true) {
      return 'jump scene_ending_true';
    }
    if (true) {
      return 'jump scene_ending_good';
    }
    if (true) {
      return 'jump scene_ending_normal';
    }
    if (true) {
      return 'jump scene_ending_bad';
    }
    return 'jump scene_ending_bad';
  }),
  ],
  'unknown': [
    'show scene #000000',
    '"BAD END - 잘못된 지목"',
    'end',
  ],
  'Start': [
    'jump scene_prologue_01',
  ]
});
