// 태풍으로 멈춘 호화 크루즈
// Generated by Mystery VN Pipeline
// 2026-01-31T10:48:33.742Z

monogatari.characters({
  "char_protagonist": {
    "name": "강지훈",
    "color": "#007bff"
  },
  "char_victim": {
    "name": "강태준",
    "color": "#dc3545"
  },
  "char_journalist": {
    "name": "김민지",
    "color": "#28a745"
  },
  "char_heiress": {
    "name": "최수연",
    "color": "#ffc107"
  },
  "char_musician": {
    "name": "박선우",
    "color": "#17a2b8"
  },
  "char_employee": {
    "name": "이수현",
    "color": "#6c757d"
  },
  "char_soundEngineer": {
    "name": "정재현",
    "color": "#343a40"
  }
});

monogatari.assets('scenes', {
  "bg_cruise_cabin": "#1a1a2e",
  "bg_cruise_deck": "#1a1a2e",
  "bg_cruise_casino": "#1a1a2e",
  "bg_cruise_emergency_exit": "#1a1a2e",
  "bg_cruise_dining": "#1a1a2e"
});

monogatari.script({
  "scene_prologue_001": [
    "show scene bg_cruise_cabin",
    "화려한 크루즈 여행의 시작. 하지만 강태준 회장의 표정은 어둡기만 하다.",
    "char_victim 김 기자, 자네가 또 무슨 꿍꿍이를 꾸미는 건지 뻔히 보인다.",
    "char_journalist 회장님이야말로 과거의 죄를 덮으려고 발버둥치는 거 아니신가요?",
    "char_victim 입 조심하는 게 좋을 거야. 자네 기자 생활, 그걸로 끝장낼 수도 있으니.",
    "강태준은 김민지를 매섭게 노려보며 경고한다. 두 사람 사이에는 팽팽한 긴장감이 감돈다.",
    "jump scene_001"
  ],
  "scene_001": [
    "show scene bg_cruise_cabin",
    "늦은 밤, 굉음과 함께 크루즈가 흔들린다. 선내 방송에서는 태풍으로 인해 항해가 지연될 것이라는 안내가 흘러나온다.",
    "char_protagonist (혼잣말) 젠장, 하필 이런 날에...",
    "잠시 후, 객실 밖에서 비명 소리가 들려온다.",
    "jump scene_002"
  ],
  "scene_002": [
    "show scene bg_cruise_cabin",
    "강태준 회장이 자신의 객실에서 흉기에 찔려 사망한 채 발견되었다. 현장은 처참하다.",
    "char_protagonist 이런... 완전히 엉망진창이군.",
    "주변에는 크루즈 직원들과 승객들이 모여 혼란스러워하고 있다.",
    "jump scene_003"
  ],
  "scene_003": [
    "show scene bg_cruise_cabin",
    "char_protagonist 저는 사립탐정 강지훈입니다. 사건 조사에 협조해주십시오.",
    "char_journalist 흥, 탐정 나셨네. 어차피 범인은 뻔하지 않나?",
    "char_protagonist 김민지 씨, 당신이 가장 먼저 용의선상에 오른 건 알고 있겠죠?",
    "char_journalist 억울하군요. 저는 그 시간에 제 객실에서 기사를 쓰고 있었습니다.",
    "jump scene_004"
  ],
  "scene_004": [
    "show scene bg_cruise_cabin",
    "char_protagonist (혼잣말) 김민지의 알리바이를 확인해봐야겠어.",
    {
      "Choice": {
        "김민지의 객실을 조사한다.": {
          "Text": "김민지의 객실을 조사한다.",
          "Do": "jump scene_005"
        },
        "주변 사람들의 증언을 듣는다.": {
          "Text": "주변 사람들의 증언을 듣는다.",
          "Do": "jump scene_006"
        }
      }
    }
  ],
  "scene_005": [
    "show scene bg_cruise_cabin",
    "김민지의 객실을 수색하던 중, 타자 소리가 녹음된 파일을 발견했다.",
    "char_protagonist (혼잣말) 반복적인 패턴... 이건 뭔가 부자연스러운데.",
    "플래그 'evidence_001' 획득.",
    "jump scene_007"
  ],
  "scene_006": [
    "show scene bg_cruise_cabin",
    "char_soundEngineer 그 시간에는 김민지 씨 객실에서 계속 타자 치는 소리가 들렸어요. 이상할 정도로요.",
    "char_protagonist (혼잣말) 역시 녹음 파일인가... 뭔가 수상해.",
    "플래그 'testimony_001' 획득.",
    "jump scene_007"
  ],
  "scene_007": [
    "show scene bg_cruise_casino",
    "char_heiress 아, 짜증나! 돈만 날렸잖아!",
    "char_protagonist 최수연 씨, 잠깐 시간 좀 내주시겠습니까?",
    "char_heiress 뭐야, 귀찮게. 난 카지노에 있었어. 알리바이 확실하다고.",
    "jump scene_008"
  ],
  "scene_008": [
    "show scene bg_cruise_casino",
    "char_protagonist (혼잣말) 최수연의 알리바이를 확인해봐야겠군.",
    {
      "Choice": {
        "카지노 직원에게 물어본다.": {
          "Text": "카지노 직원에게 물어본다.",
          "Do": "jump scene_009"
        },
        "최수연의 행적을 추적한다.": {
          "Text": "최수연의 행적을 추적한다.",
          "Do": "jump scene_010"
        }
      }
    }
  ],
  "scene_009": [
    "show scene bg_cruise_casino",
    "카지노 직원 최수연 씨는 그 시간에 확실히 카지노에 계셨습니다. 많은 사람들이 봤을 겁니다.",
    "char_protagonist (혼잣말) 최수연은 일단 용의선상에서 제외해야겠군.",
    "플래그 'testimony_002' 획득.",
    "jump scene_011"
  ],
  "scene_010": [
    "show scene bg_cruise_casino",
    "최수연은 정말로 사건 발생 시각에 카지노에 있었던 것으로 보인다. 그녀의 알리바이는 꽤나 확실하다.",
    "char_protagonist (혼잣말) 최수연은 일단 보류다.",
    "jump scene_011"
  ],
  "scene_011": [
    "show scene bg_cruise_deck",
    "char_protagonist (혼잣말) 뭔가 이상해. 김민지의 알리바이가 완벽하지 않아. 다른 가능성을 찾아봐야 해.",
    {
      "Choice": {
        "비상 통로를 조사한다.": {
          "Text": "비상 통로를 조사한다.",
          "Do": "jump scene_012"
        },
        "피해자의 객실을 다시 조사한다.": {
          "Text": "피해자의 객실을 다시 조사한다.",
          "Do": "jump scene_013"
        }
      }
    }
  ],
  "scene_012": [
    "show scene bg_cruise_emergency_exit",
    "크루즈 내부의 비상 통로를 조사하던 중, 최근에 사용된 듯한 먼지를 발견했다.",
    "char_protagonist (혼잣말) 비상 통로... 누군가 이 길을 이용했다는 건가?",
    "플래그 'evidence_002' 획득.",
    "jump scene_014"
  ],
  "scene_013": [
    "show scene bg_cruise_cabin",
    "char_protagonist (혼잣말) 뭔가 놓친 게 있을 거야. 다시 한번 꼼꼼히 살펴봐야 해.",
    "피해자의 객실을 다시 조사했지만, 새로운 단서는 발견되지 않았다.",
    "jump scene_014"
  ],
  "scene_014": [
    "show scene bg_cruise_cabin",
    "char_protagonist (혼잣말) 비상 통로... 타자 소리 녹음 파일... 뭔가 연결고리가 있을 텐데.",
    {
      "Choice": {
        "객실 관리인에게 문의한다.": {
          "Text": "객실 관리인에게 문의한다.",
          "Do": "jump scene_015"
        },
        "이수현 비서를 조사한다.": {
          "Text": "이수현 비서를 조사한다.",
          "Do": "jump scene_016"
        }
      }
    }
  ],
  "scene_015": [
    "show scene bg_cruise_cabin",
    "객실 관리인 회장님 객실 문은 자동 잠금 장치가 달려있습니다. 그런데 가끔 오작동을 일으키기도 합니다.",
    "char_protagonist (혼잣말) 자동 잠금 장치... 오작동... 드디어 퍼즐이 맞춰지는군.",
    "플래그 'evidence_003' 획득.",
    "jump scene_017"
  ],
  "scene_016": [
    "show scene bg_cruise_cabin",
    "char_employee 저는 회장님께 충성을 다했습니다. 정말입니다.",
    "char_protagonist (혼잣말) 뭔가 숨기고 있는 것 같지만, 결정적인 증거는 없어.",
    "이수현은 여전히 침착한 태도를 유지하고 있다.",
    "jump scene_017"
  ],
  "scene_017": [
    "show scene bg_cruise_cabin",
    "char_protagonist (혼잣말) 김민지가 범인이라는 심증은 굳어졌지만, 결정적인 증거가 필요해.",
    {
      "Choice": {
        "김민지의 객실을 다시 수색한다.": {
          "Text": "김민지의 객실을 다시 수색한다.",
          "Do": "jump scene_018"
        },
        "사건을 재구성해본다.": {
          "Text": "사건을 재구성해본다.",
          "Do": "jump scene_019"
        }
      }
    }
  ],
  "scene_018": [
    "show scene bg_cruise_cabin",
    "김민지의 객실을 다시 수색하던 중, 만년필에서 강태준의 혈흔을 발견했다!",
    "char_protagonist 이걸로 끝이다, 김민지!",
    "플래그 'evidence_004' 획득.",
    "jump scene_deduction_start"
  ],
  "scene_019": [
    "show scene bg_cruise_cabin",
    "사건을 재구성해본 결과, 김민지가 범인이라는 결론에 도달했다.",
    "char_protagonist 이제 모든 게 명확해졌어.",
    "jump scene_deduction_start"
  ],
  "scene_deduction_start": [
    "show scene bg_cruise_deck",
    "모든 단서가 모였다. 이제 진실을 밝힐 시간이다.",
    "char_protagonist 자, 이제 누가 범인인지 맞춰볼까."
  ],
  "scene_ending_true": [
    "show scene bg_cruise_deck",
    "김민지는 자신의 죄를 인정했다. 그녀는 강태준의 악행을 세상에 알리고 싶었지만, 결국 살인이라는 잘못된 길을 선택했다.",
    "char_protagonist 정의를 실현하는 방법은 살인이 아니었어.",
    "사건은 해결되었지만, 강지훈의 마음은 무겁기만 하다."
  ],
  "scene_ending_normal": [
    "show scene bg_cruise_deck",
    "강지훈은 범인을 잡았지만, 사건의 진실은 여전히 미궁 속에 남아있다.",
    "char_protagonist 이게 최선이었을까...",
    "찝찝한 기분으로 강지훈은 크루즈를 떠난다."
  ],
  "scene_ending_bad1": [
    "show scene bg_cruise_deck",
    "강지훈은 엉뚱한 사람을 범인으로 지목했다. 진범은 유유히 크루즈를 빠져나간다.",
    "char_protagonist 내가 틀렸어...",
    "실패감에 휩싸인 강지훈은 탐정으로서의 자질에 회의감을 느낀다."
  ],
  "scene_ending_bad2": [
    "show scene bg_cruise_deck",
    "충분한 단서를 찾지 못한 강지훈은 사건을 미해결 상태로 남겨둔 채 크루즈를 떠난다.",
    "char_protagonist 이번 사건은 실패다...",
    "강지훈은 과거 해결하지 못했던 사건의 악몽에 다시 시달리게 된다."
  ],
  "Start": [
    "jump scene_prologue_001"
  ]
});
