// 태풍으로 멈춘 호화 크루즈 빅토리아호
// Generated by Mystery VN Pipeline
// 2026-01-31T11:53:38.613Z

const { monogatari } = window;

// 캐릭터 정의
monogatari.characters({
  "char_protagonist": {
    "name": "강지훈",
    "color": "#000000"
  },
  "char_victim": {
    "name": "김민준",
    "color": "#800000"
  },
  "char_employee": {
    "name": "박철수",
    "color": "#A9A9A9"
  },
  "char_secretary": {
    "name": "최수지",
    "color": "#FF69B4"
  },
  "char_doctor": {
    "name": "이현우",
    "color": "#008080"
  },
  "char_celebrity": {
    "name": "고아라",
    "color": "#DA70D6"
  },
  "char_writer": {
    "name": "조현우",
    "color": "#8B4513"
  }
});

// 배경 정의 (색상)
monogatari.assets('scenes', {
  "bg_cruise_ship": "#1a1a2e",
  "bg_victim_room": "#1a1a2e",
  "bg_culprit_room": "#1a1a2e",
  "bg_cruise_bar": "#1a1a2e",
  "bg_cruise_library": "#1a1a2e",
  "bg_cruise_medical": "#1a1a2e"
});

// 스크립트
monogatari.script({
  "scene_prologue_001": [
    "show scene bg_cruise_ship",
    "나는 강지훈. 프리랜서 탐정이다. 모처럼 휴가를 내어 호화 크루즈, 빅토리아호에 몸을 실었다.",
    "드넓은 바다를 가르며 나아가는 크루즈. 낭만적인 여행이 시작될 줄 알았다.",
    "jump scene_prologue_002"
  ],
  "scene_prologue_002": [
    "show scene bg_cruise_ship",
    "char_victim 똑바로 안 해?! 이딴 식으로 일할 거면 당장 그만둬!",
    "갑판 위에서 한 남자가 직원에게 고함을 지르고 있었다. 김민준. 대형 건설사 사장이라고 했던가. 오만함이 얼굴에 가득 묻어나는 남자였다.",
    "저 남자는 어딘가 불길하다….",
    "jump scene_001"
  ],
  "scene_001": [
    "show scene bg_cruise_ship",
    "다음 날 아침, 선내 방송이 울려 퍼졌다.",
    "선내 방송 승객 여러분께 알립니다. 안타깝게도 김민준 사장님께서 객실에서 숨진 채 발견되었습니다. 현재 경찰이 수사 중이며, 승객 여러분의 협조를 부탁드립니다.",
    "결국, 사건이 터지고 말았다….",
    "jump scene_002"
  ],
  "scene_002": [
    "show scene bg_cruise_ship",
    "사건 현장으로 향했다. 객실 문은 굳게 닫혀 있었다.",
    "경찰 탐정님이십니까? 안으로 들어오시죠.",
    "객실 안은 엉망진창이었다. 고급 가구들이 부서져 있었고, 바닥에는 핏자국이 선명했다.",
    "jump scene_003"
  ],
  "scene_003": [
    "show scene bg_victim_room",
    "피해자는 침대에 쓰러져 있었다. 날카로운 흉기에 찔린 듯했다.",
    "(주변을 둘러본다) 뭔가 이상하다….",
    {
      "Choice": {
        "피해자의 시신": {
          "Text": "피해자의 시신",
          "Do": "jump scene_004"
        },
        "객실 내부": {
          "Text": "객실 내부",
          "Do": "jump scene_005"
        }
      }
    }
  ],
  "scene_004": [
    "show scene bg_victim_room",
    "피해자의 상처를 자세히 살펴본다. 깊고 날카로운 자상이다.",
    "저항한 흔적이 보인다. 격렬한 몸싸움이 있었던 것 같다.",
    "jump scene_005"
  ],
  "scene_005": [
    "show scene bg_victim_room",
    "객실 내부를 꼼꼼히 살펴본다.",
    "테이블 위에 놓인 술잔이 눈에 띈다. 누군가와 함께 술을 마신 것일까?",
    "바닥에 떨어진 흉기를 발견했다.",
    "(흉기를 조사한다)",
    "혈흔이 묻어 있는 흉기다. 손잡이에 지문이 묻어 있다.",
    "**[증거 획득: 혈흔이 묻은 흉기 (ev_003)]**",
    "jump scene_006"
  ],
  "scene_006": [
    "show scene bg_culprit_room",
    "첫 번째 용의자는 박철수. 김민준의 회사 전 직원이다.",
    "char_protagonist 박철수 씨, 어젯밤에 무엇을 하고 있었습니까?",
    "char_employee 저는 제 방에서 잠을 자고 있었습니다. 태풍 때문에 파도 소리가 너무 심해서 잠을 설쳤습니다.",
    "char_protagonist 정말입니까? 혹시 다른 사람과 연락하거나 만난 적은 없습니까?",
    "char_employee 아니요, 아무도 만나지 않았습니다. 저는 계속 방에 있었습니다.",
    "수상하다. 뭔가 숨기는 것 같은데…",
    "jump scene_007"
  ],
  "scene_007": [
    "show scene bg_cruise_bar",
    "다음 용의자는 최수지. 김민준의 비서이다.",
    "char_protagonist 최수지 씨, 어젯밤에 무엇을 하고 있었습니까?",
    "char_secretary 저는 크루즈 바에서 술을 마시고 있었어요. 사장님 때문에 스트레스를 너무 많이 받아서요.",
    "char_protagonist 혼자서요?",
    "char_secretary 네, 혼자서요. 바텐더에게 물어보시면 아실 거예요.",
    "(최수지를 살펴본다) 화려한 옷차림과 짙은 화장이 눈에 띈다. 어딘가 불안해 보인다.",
    "jump scene_008"
  ],
  "scene_008": [
    "show scene bg_cruise_medical",
    "다음 용의자는 이현우. 크루즈 전담 의사이다.",
    "char_protagonist 이현우 씨, 어젯밤에 무엇을 하고 있었습니까?",
    "char_doctor 저는 환자를 진료하고 있었습니다. 태풍 때문에 몸이 안 좋은 승객들이 많았습니다.",
    "char_protagonist 진료 기록을 보여주시겠습니까?",
    "char_doctor 물론입니다. 여기 있습니다.",
    "(진료 기록을 살펴본다) 꼼꼼하게 작성되어 있지만, 어딘가 부자연스럽다….",
    "jump scene_009"
  ],
  "scene_009": [
    "show scene bg_culprit_room",
    "박철수의 방을 다시 조사하기로 했다.",
    "방 안은 좁고 간소했다. 특별한 것은 없어 보인다.",
    "스피커폰이 눈에 띈다.",
    "(스피커폰을 조사한다)",
    "음질이 좋지 않다. 마치 녹음된 소리를 재생하는 것 같다.",
    "**[증거 획득: 스피커폰 (ev_001)]**",
    "jump scene_010"
  ],
  "scene_010": [
    "show scene bg_culprit_room",
    "노트북을 발견했다. 혹시…?",
    "(노트북을 켠다)",
    "음성 녹음 파일이 있다. 박철수의 목소리다.",
    "(녹음 파일을 들어본다)",
    "“저는 지금 방에서 쉬고 있습니다. 밖에 태풍 때문에 너무 시끄럽네요.” 어색하다. 너무 부자연스럽다!",
    "**[증거 획득: 녹음 파일 (ev_002)]**",
    "jump scene_011"
  ],
  "scene_011": [
    "show scene bg_cruise_bar",
    "최수지의 알리바이를 확인하기 위해 바텐더를 찾아갔다.",
    "char_protagonist 어젯밤에 최수지 씨가 여기서 술을 마셨다고 하는데, 기억하십니까?",
    "바텐더 네, 기억합니다. 혼자 오셔서 칵테일을 몇 잔 드셨어요.",
    "char_protagonist 혹시 다른 특이한 점은 없었나요?",
    "바텐더 글쎄요… 평소보다 조금 초조해 보이긴 했습니다.",
    "jump scene_012"
  ],
  "scene_012": [
    "show scene bg_cruise_medical",
    "이현우의 진료 기록을 다시 확인하기로 했다.",
    "진료를 받았다는 승객들을 찾아 심문했다.",
    "승객 1 저는 어젯밤에 의사 선생님께 진료를 받지 않았습니다.",
    "승객 2 저도 마찬가지입니다. 몸이 안 좋았지만, 그냥 방에서 쉬었습니다.",
    "진료 기록이 조작된 것이 분명하다!",
    "jump scene_013"
  ],
  "scene_013": [
    "show scene bg_cruise_ship",
    "고아라를 심문한다.",
    "char_protagonist 고아라 씨, 어젯밤에 무엇을 하고 있었습니까?",
    "char_celebrity 전 영화를 보고 있었어요. 매니저가 증언해 줄 수 있을 거예요.",
    "매니저 맞습니다. 제가 같이 있었어요.",
    "jump scene_014"
  ],
  "scene_014": [
    "show scene bg_cruise_library",
    "조현우를 심문한다.",
    "char_protagonist 조현우 씨, 어젯밤에 무엇을 하고 있었습니까?",
    "char_writer 도서관에서 책을 읽고 있었습니다. 직원이 증언해 줄 수 있을 겁니다.",
    "도서관 직원 맞습니다. 제가 봤습니다.",
    "jump scene_015"
  ],
  "scene_015": [
    "show scene bg_cruise_ship",
    "이제 모든 단서가 모였다. 사건을 재구성해 보자.",
    "박철수는 녹음 파일을 이용해 알리바이를 조작했다. 스피커폰의 음질이 좋지 않았고, 녹음 파일의 내용도 어색했다.",
    "최수지는 바텐더의 증언으로 알리바이가 입증되었다.",
    "이현우는 진료 기록을 조작했지만, 알리바이는 거짓으로 드러났다.",
    "고아라와 조현우는 매니저와 도서관 직원의 증언으로 알리바이가 입증되었다.",
    "결정적으로, 흉기에서 박철수의 지문이 발견되었다.",
    "jump scene_deduction_start"
  ],
  "scene_deduction_start": [
    "show scene bg_cruise_ship",
    "이제 모든 것을 종합하여 범인을 밝혀낼 시간이다."
  ],
  "scene_ending_true": [
    "show scene bg_cruise_ship",
    "char_protagonist 범인은 박철수 씨입니다! 그는 녹음 파일을 이용해 알리바이를 조작했고, 흉기에서 그의 지문이 나왔습니다. 그의 동기는 과거 김민준 사장의 비윤리적인 사업 방식으로 인해 가족이 파산하고 억울하게 죽었기 때문입니다.",
    "char_employee …결국, 들키고 말았군요. 맞습니다. 제가 죽였습니다. 그 놈은 제 가족을 파멸로 몰아넣은 악마였습니다!",
    "진실은 밝혀졌다. 하지만 박철수의 슬픔은 쉽게 가시지 않을 것이다."
  ],
  "scene_ending_normal": [
    "show scene bg_cruise_ship",
    "char_protagonist 범인은… 글쎄, 아직 모르겠습니다. 증거가 부족합니다.",
    "사건은 미궁 속으로 빠지고 말았다. 나는 씁쓸한 마음으로 크루즈를 떠났다."
  ],
  "scene_ending_bad1": [
    "show scene bg_cruise_ship",
    "char_protagonist 범인은… 당신입니다! (잘못된 용의자 지목)",
    "잘못된 용의자 무슨 근거로 그런 말씀을 하시는 거죠? 저는 결백합니다!"
  ],
  "Start": [
    "jump scene_prologue_001"
  ]
});
