// 산장의 비밀
// Generated by Mystery VN Pipeline (Text Only)
// 2026-01-31T09:48:46.623Z

// 캐릭터 정의 (텍스트 전용)
monogatari.characters({
  "char_protagonist": {
    "name": "김민지",
    "color": "#007bff"
  },
  "char_sunyoung": {
    "name": "박선영",
    "color": "#6c757d"
  },
  "char_minsoo": {
    "name": "최민수",
    "color": "#28a745"
  },
  "char_jihoon": {
    "name": "김지훈",
    "color": "#dc3545"
  },
  "char_seojin": {
    "name": "이서진",
    "color": "#ffc107"
  },
  "char_yuna": {
    "name": "한유나",
    "color": "#17a2b8"
  },
  "char_victim": {
    "name": "강태준",
    "color": "#343a40"
  }
});

// 배경 정의 (색상만)
monogatari.assets('scenes', {
  "bg_mountain_lodge_livingroom": "#1a1a2e",
  "bg_mountain_lodge_room": "#1a1a2e",
  "bg_mountain_lodge_study": "#1a1a2e"
});

// 스크립트
monogatari.script({
  "scene_prologue_001": [
    "show scene bg_mountain_lodge_livingroom",
    "폭설이 쏟아지는 산장, 나는 취재를 위해 건축가 강태준을 만나러 왔다.",
    "char_protagonist (강태준 씨는 어떤 사람일까...)",
    "jump scene_prologue_002"
  ],
  "scene_prologue_002": [
    "show scene bg_mountain_lodge_livingroom",
    "char_victim 박선영 씨, 그 설계안은 도대체 뭡니까? 엉망진창이군요!",
    "char_sunyoung 죄송합니다, 강태준 대표님. 수정하겠습니다.",
    "char_victim 수정? 당신은 재능이 없어. 그냥 그만두는 게 어떻소?",
    "강태준은 박선영에게 모욕적인 말을 퍼부었다. 차가운 분위기가 감돌았다.",
    "char_protagonist (저렇게 심하게 말할 필요가 있을까...)",
    "jump scene_incident_001"
  ],
  "scene_incident_001": [
    "show scene bg_mountain_lodge_livingroom",
    "다음 날 아침, 강태준이 사라졌다. 그의 방은 잠겨 있었고, 문을 강제로 열자 그는 침대에서 칼에 찔린 채 발견되었다.",
    "char_protagonist 맙소사! 살인사건이야!",
    "jump scene_investigation_001"
  ],
  "scene_investigation_001": [
    "show scene bg_mountain_lodge_room",
    "나는 사건 현장을 조사하기 시작했다. 방은 어수선했고, 흉기는 강태준의 옆에 떨어져 있었다.",
    "피해자의 일기장이 눈에 띈다.",
    {
      "Choice": {
        "본다": {
          "Text": "본다",
          "Do": "jump scene_investigation_002"
        },
        "보지 않는다": {
          "Text": "보지 않는다",
          "Do": "jump scene_investigation_003"
        }
      }
    }
  ],
  "scene_investigation_002": [
    "show scene bg_mountain_lodge_room",
    "일기장에는 박선영을 향한 강태준의 악감정이 자세히 적혀 있었다. '저 무능한 여자가 감히 내 작품을 망치려 하다니', '반드시 쫓아내야 한다'...",
    "char_protagonist (박선영 씨가 범인일까? 하지만 동기만으로는...)",
    "jump scene_investigation_003"
  ],
  "scene_investigation_003": [
    "show scene bg_mountain_lodge_livingroom",
    "나는 다른 사람들을 심문하기 시작했다.",
    {
      "Choice": {
        "박선영": {
          "Text": "박선영",
          "Do": "jump scene_sunyoung_interview_001"
        },
        "최민수": {
          "Text": "최민수",
          "Do": "jump scene_minsoo_interview_001"
        },
        "김지훈": {
          "Text": "김지훈",
          "Do": "jump scene_jihoon_interview_001"
        },
        "이서진": {
          "Text": "이서진",
          "Do": "jump scene_seojin_interview_001"
        },
        "한유나": {
          "Text": "한유나",
          "Do": "jump scene_yuna_interview_001"
        }
      }
    }
  ],
  "scene_sunyoung_interview_001": [
    "show scene bg_mountain_lodge_livingroom",
    "char_protagonist 박선영 씨, 사건 당시에 어디에 계셨나요?",
    "char_sunyoung 제 방에서 책을 읽고 있었습니다. 라디오를 켜놓고 있어서, 다른 사람들도 들었을 거예요.",
    "char_protagonist (알리바이가 있는 건가...)",
    {
      "Choice": {
        "물어본다": {
          "Text": "물어본다",
          "Do": "jump scene_sunyoung_interview_002"
        },
        "다른 질문을 한다": {
          "Text": "다른 질문을 한다",
          "Do": "jump scene_investigation_003"
        }
      }
    }
  ],
  "scene_sunyoung_interview_002": [
    "show scene bg_mountain_lodge_livingroom",
    "char_protagonist 라디오는 언제 켜셨나요?",
    "char_sunyoung 밤 11시쯤에요. 타이머를 맞춰놓고 잤어요.",
    "char_protagonist (타이머...? 뭔가 이상한데...)",
    "jump scene_investigation_003"
  ],
  "scene_minsoo_interview_001": [
    "show scene bg_mountain_lodge_livingroom",
    "char_protagonist 최민수 씨, 사건 당시에 어디에 계셨나요?",
    "char_minsoo 거실에서 TV를 보고 있었어요. 밤 11시쯤에는 박선영 씨 방에서 라디오 소리가 들리던데요.",
    "char_protagonist (박선영 씨의 알리바이를 증명해주는 건가...?)",
    "jump scene_investigation_003"
  ],
  "scene_jihoon_interview_001": [
    "show scene bg_mountain_lodge_livingroom",
    "char_protagonist 김지훈 씨, 사건 당시에 어디에 계셨나요?",
    "char_jihoon 제 방에서 자고 있었어요...",
    "jump scene_investigation_003"
  ],
  "scene_seojin_interview_001": [
    "show scene bg_mountain_lodge_livingroom",
    "char_protagonist 이서진 씨, 사건 당시에 어디에 계셨나요?",
    "char_seojin 서재에서 책을 읽고 있었습니다.",
    "jump scene_investigation_003"
  ],
  "scene_yuna_interview_001": [
    "show scene bg_mountain_lodge_livingroom",
    "char_protagonist 한유나 씨, 사건 당시에 어디에 계셨나요?",
    "char_yuna 제 방에서 쉬고 있었어요.",
    "jump scene_investigation_003"
  ],
  "scene_investigation_004": [
    "show scene bg_mountain_lodge_room",
    "나는 박선영의 방에 있는 라디오를 조사하기로 했다.",
    {
      "Choice": {
        "살펴본다": {
          "Text": "살펴본다",
          "Do": "jump scene_investigation_005"
        },
        "살펴보지 않는다": {
          "Text": "살펴보지 않는다",
          "Do": "jump scene_investigation_006"
        }
      }
    }
  ],
  "scene_investigation_005": [
    "show scene bg_mountain_lodge_room",
    "라디오에는 타이머 기능이 있었다. 타이머는 23시에 맞춰져 있었다.",
    "전원 스위치에는 희미하게 지문이 묻어 있다.",
    "char_protagonist (밤 11시면... 박선영 씨가 주장하는 시간과 같잖아? 하지만 타이머를 맞춰놨다면...)",
    "jump scene_investigation_006"
  ],
  "scene_investigation_006": [
    "show scene bg_mountain_lodge_room",
    "피해자의 방에서 흉기를 다시 확인한다.",
    "칼날은 깨끗하게 닦여져 있다.",
    "char_protagonist (이 칼은 어디에서 가져온 걸까?)",
    "jump scene_deduction_start"
  ],
  "scene_deduction_start": [
    "show scene bg_mountain_lodge_livingroom",
    "모든 증거와 증언을 종합해 볼 때, 범인은..."
  ],
  "scene_ending_true": [
    "show scene bg_mountain_lodge_livingroom",
    "박선영은 결국 범행을 인정했다. 그녀는 강태준의 갑질과 과거 표절로 인한 좌절감에 복수심을 품고 있었다.",
    "char_sunyoung 저는... 저는 어쩔 수 없었어요..."
  ],
  "scene_ending_normal": [
    "show scene bg_mountain_lodge_livingroom",
    "결정적인 증거 부족으로 사건은 미해결로 남았다. 하지만 나는 박선영의 슬픈 눈빛을 잊을 수 없었다."
  ],
  "scene_ending_bad1": [
    "show scene bg_mountain_lodge_livingroom",
    "나는 엉뚱한 사람을 범인으로 지목했다. 진실은 영원히 묻히고 말았다."
  ],
  "scene_ending_bad2": [
    "show scene bg_mountain_lodge_livingroom",
    "나는 충분한 단서를 찾지 못했다. 사건은 미궁 속으로 빠졌다."
  ],
  "Start": [
    "jump scene_prologue_001"
  ]
});
