// 폭풍의 항해: 오리온호 살인사건
// Generated by Mystery VN Pipeline (Kamaitachi Style)
// 2026-02-01T10:46:27.407Z

'use strict';

// ========================================
// Storage 초기화 (플래그 시스템)
// ========================================
monogatari.storage({
  "clue_count": 0,
  "st_correct_culprit": false,
  "st_correct_trick": false,
  "st_correct_motive": false,
  "st_wrong_accusation": false,
  "ev_oily_footprint": false,
  "ev_logbook": false,
  "ev_blackmail_note": false,
  "ev_hidden_recorder": false,
  "ts_culprit_alibi": false,
  "ts_suspect1_alibi": false,
  "ts_witness_sighting": false,
  "ts_harassment": false,
  "vs_captain_room": false,
  "vs_engine_room": false,
  "vs_casino": false,
  "st_found_body": false,
  "vs_deck": false,
  "vs_dining_hall": false,
  "correct_culprit": false,
  "correct_trick": false,
  "correct_motive": false
});

// ========================================
// 캐릭터 정의
// ========================================
monogatari.characters({
  "char_protagonist": {
    "name": "김지운",
    "color": "#E0E0E0"
  },
  "char_culprit": {
    "name": "윤서진",
    "color": "#A0C4FF"
  },
  "char_suspect1": {
    "name": "박선우",
    "color": "#FFADAD"
  },
  "char_suspect2": {
    "name": "최유리",
    "color": "#FFD6A5"
  },
  "char_suspect3": {
    "name": "이정훈",
    "color": "#FDFFB6"
  },
  "char_victim": {
    "name": "강태준",
    "color": "#BDB2FF"
  }
});

// ========================================
// 배경 정의
// ========================================
monogatari.assets('scenes', {
  "bg_captain_room": "#192A56",
  "bg_engine_room": "#2F3640",
  "bg_casino": "#8C2A3C",
  "bg_deck": "#2C3E50",
  "bg_dining_hall": "#4A4A4A"
});

monogatari.assets ('music', {
    'main_bgm': 'bgm/dreamy-flashback.mp3'
});


// ========================================
// 스크립트
// ========================================
monogatari.script({
  'scene_prologue_01': [
    'show scene bg_dining_hall',
    '북태평양을 가로지르는 호화 크루즈 \'오리온호\'. 나는 차기작 구상을 위해 이 배에 올랐다.',
    '하지만 망망대해 위에서의 낭만도 잠시, 거대한 태풍이 오리온호를 집어삼키려 하고 있었다.',
    'char_victim 최유리 씨, 이런 날은 둘이서 와인이나 한잔하면 좋지 않겠어? 내 방에 아주 좋은 게 있는데.',
    'char_suspect2 관심 없어요, 선장님. 배나 제대로 신경 쓰시죠.',
    '가수 최유리는 혐오감이 가득한 얼굴로 선장을 쏘아붙이고는 자리를 떠났다. 선장의 평판은 그리 좋아 보이지 않았다.',
    'jump scene_prologue_02',
  ],
  'scene_prologue_02': [
    'show scene bg_deck',
    '바람을 쐬러 나온 갑판은 이미 거친 비바람이 몰아치고 있었다.',
    'char_suspect3 이런, 폭풍이 생각보다 더 거세군요. 이런 날은 잠들기도 쉽지 않겠어요.',
    '온화한 인상의 노신사, 이정훈 씨가 내게 말을 걸어왔다. 그때, 선장실 쪽에서 고성이 터져 나왔다.',
    'char_suspect1 이건 약속이랑 다르잖소! 당장 내 물건부터 처리해 줘요!',
    'char_victim 시끄럽소, 박 사장. 이 배에선 내가 왕이야. 돈을 더 가져오든가, 아니면 조용히 하든가.',
    '사업가 박선우가 핏발 선 눈으로 선장을 노려보고 있었다. 두 사람 사이에도 심상치 않은 기류가 흘렀다.',
    'jump scene_prologue_03',
  ],
  'scene_prologue_03': [
    'show scene bg_deck',
    '박선우가 분을 삭이지 못하고 떠난 뒤, 1등 항해사 윤서진이 선장에게 다가갔다.',
    'char_culprit 선장님, 태풍 대비 보고 드립니다. 기관실 비상 설비 점검이 필요할 것 같습니다.',
    'char_victim 알아서 해. 쯧, 자네 아비처럼 무능하게 배나 가라앉히지 말고.',
    '선장의 모욕적인 말에, 윤서진 항해사의 표정이 순간 얼어붙었다. 그녀는 아무 말 없이 고개를 숙이고 자리를 떠났다.',
    '폭풍우가 몰아치는 배 안에서, 저마다의 갈등이 파도처럼 일렁이고 있었다. 그리고 이것이 내가 선장을 본 마지막 모습이었다.',
    'jump scene_incident_01',
  ],
  'scene_incident_01': [
    'show scene bg_dining_hall',
    '다음 날 아침, 배는 여전히 폭풍의 영향권 안에 있었다. 승객들은 불안감 속에서 식당에 모여들었다.',
    'char_suspect1 선장은 어디 있는 거야? 배가 이 모양인데 코빼기도 안 보이다니!',
    'char_culprit 선장님께서 응답이 없으십니다. 계속 호출하고 있지만...',
    '그때, 한 승무원이 새파랗게 질린 얼굴로 식당에 뛰어 들어왔다.',
    'char_culprit 무슨 일이지?',
    '"서... 선장실 문이 열려 있는데... 피가..."',
    'jump scene_incident_02',
  ],
  'scene_incident_02': [
    'show scene bg_captain_room',
    function() {
          const flags = JSON.parse('{\"st_found_body\":true}');
          const s = monogatari.storage();
          for (const [k, v] of Object.entries(flags)) {
            s[k] = v;
          }
          monogatari.storage(s);
        },
    '강태준 선장은 자신의 방, 그 화려한 집무용 책상에 쓰러져 있었다. 가슴에는 날카로운 흉기가 남긴 단 하나의 자상이 선명했다.',
    'char_protagonist (사망 추정 시각은 어젯밤... 태풍이 가장 심할 때로군.)',
    'char_culprit 외부와의 통신은 두절 상태입니다. 구조 신호도 보낼 수 없습니다. 이 배 안의 누군가가... 범인입니다.',
    '고립된 크루즈, 폭풍 속의 살인. 원치 않았지만, 나의 추리가 시작되어야만 했다.',
    'jump scene_investigation_hub_1',
  ],
  'scene_investigation_hub_1': [
    'show scene bg_dining_hall',
    '1차 수사를 시작한다. 어디를 먼저 조사할까?',
    {
      'Choice': {
        '사건 현장인 [선장실]을 조사한다.': {
          'Condition': (function() { return monogatari.storage().vs_captain_room !== true; }),
          'Do': 'jump scene_investigate_captain_room_1'
        },
        '알리바이를 주장하는 [기관실]을 조사한다.': {
          'Condition': (function() { return monogatari.storage().vs_engine_room !== true; }),
          'Do': 'jump scene_investigate_engine_room_1'
        },
        '박선우가 있었다는 [카지노]를 조사한다.': {
          'Condition': (function() { return monogatari.storage().vs_casino !== true; }),
          'Do': 'jump scene_investigate_casino_1'
        },
        '목격자를 찾으러 [갑판]으로 가본다.': {
          'Condition': (function() { return monogatari.storage().vs_deck !== true; }),
          'Do': 'jump scene_investigate_deck_1'
        },
        '다른 용의자들이 있는 [식당]으로 가본다.': {
          'Condition': (function() { return monogatari.storage().vs_dining_hall !== true; }),
          'Do': 'jump scene_investigate_dining_hall_1'
        }
      }
    },
  ],
  'scene_investigate_captain_room_1': [
    'show scene bg_captain_room',
    function() {
          const flags = JSON.parse('{\"vs_captain_room\":true}');
          const s = monogatari.storage();
          for (const [k, v] of Object.entries(flags)) {
            s[k] = v;
          }
          monogatari.storage(s);
        },
    '선장실은 여전히 어지럽다. 시신은 옮겨졌지만, 비릿한 냄새는 가시지 않았다.',
    '나는 주변을 샅샅이 살폈다.',
    '쓰레기통에서 찢어진 종이 조각을 발견했다. 이어 붙여보니 \'밀수... 약속한 금액을 당장...\'이라는 글자가 보인다.',
    'char_protagonist (선장이 박선우 씨를 협박하고 있었던 건가... 강력한 동기가 되겠군.)',
    '그리고... 문 앞 카펫에서 아주 희미한 자국을 발견했다. 기름때가 묻은 발자국 같다.',
    'char_protagonist (이 기름... 어디서 본 것 같은데. 기관실에서 쓰는 윤활유와 비슷하다.)',
    'jump scene_investigation_hub_2',
  ],
  'scene_investigate_engine_room_1': [
    'show scene bg_engine_room',
    function() {
          const flags = JSON.parse('{\"vs_engine_room\":true}');
          const s = monogatari.storage();
          for (const [k, v] of Object.entries(flags)) {
            s[k] = v;
          }
          monogatari.storage(s);
        },
    '기관실은 귀가 먹먹할 정도의 굉음과 뜨거운 열기로 가득했다. 윤서진 항해사가 묵묵히 계기판을 살피고 있었다.',
    'char_protagonist 윤서진 씨, 어젯밤 알리바이에 대해 다시 한번 들을 수 있을까요?',
    'char_culprit 어제 말씀드린 그대로입니다. 22시 30분부터 23시 30분까지, 이곳에서 비상 설비를 점검했습니다. 여기 운행 일지가 증거입니다.',
    '그녀가 내민 일지에는 빽빽한 기록이 적혀 있었다. 23:00 정각에는 \'3번 터빈 압력 정상\'이라고 쓰여 있다.',
    '나는 일지를 유심히 살펴보았다. 무언가 위화감이 느껴진다.',
    'char_protagonist (23시 기록만... 주변의 다른 기록들과 잉크의 마른 상태가 미묘하게 달라 보인다. 마치 나중에 급하게 써넣은 것처럼...)',
    'jump scene_investigation_hub_2',
  ],
  'scene_investigate_casino_1': [
    'show scene bg_casino',
    function() {
          const flags = JSON.parse('{\"vs_casino\":true}');
          const s = monogatari.storage();
          for (const [k, v] of Object.entries(flags)) {
            s[k] = v;
          }
          monogatari.storage(s);
        },
    '카지노는 사건 때문인지 한산했다. 박선우가 초조하게 손톱을 물어뜯으며 앉아 있었다.',
    'char_protagonist 박선우 씨, 어젯밤 23시경에 이곳에 계셨다고 들었습니다.',
    'char_suspect1 그래! 여기 딜러도 봤고, 다른 손님들도 봤어! 그 영감탱이 때문에 머리는 복잡했지만, 난 사람 죽일 배짱은 없다고!',
    '그는 신경질적으로 소리쳤다. 딜러에게 확인해보니, 그의 알리바이는 확실해 보였다.',
    'char_protagonist (알리바이는 확실한가... 하지만 선장과 금전 문제가 있었던 건 분명해 보인다.)',
    'jump scene_investigation_hub_2',
  ],
  'scene_investigate_deck_1': [
    'show scene bg_deck',
    function() {
          const flags = JSON.parse('{\"vs_deck\":true}');
          const s = monogatari.storage();
          for (const [k, v] of Object.entries(flags)) {
            s[k] = v;
          }
          monogatari.storage(s);
        },
    '갑판에는 이정훈 씨가 나와 바다를 보고 있었다.',
    'char_protagonist 이정훈 선생님, 어젯밤 혹시 무언가 보신 게 있으신가요?',
    'char_suspect3 글쎄요... 제가 불면증이 있어서 밤새 배 안을 좀 돌아다녔습니다. 그러다 23시가 되기 직전이었을 겁니다.',
    'char_suspect3 승무원 복장을 한 사람이 3층 복도 끝에 있는 창고 같은 문으로 휙 사라지는 걸 봤어요. 어두워서 얼굴은 못 봤지만, 체격은 그리 크지 않은 사람이었죠.',
    '나는 그의 증언을 기억해두었다. 승무원만 아는 통로 같은 것이 있을지도 모른다.',
    'jump scene_investigation_hub_2',
  ],
  'scene_investigate_dining_hall_1': [
    'show scene bg_dining_hall',
    function() {
          const flags = JSON.parse('{\"vs_dining_hall\":true}');
          const s = monogatari.storage();
          for (const [k, v] of Object.entries(flags)) {
            s[k] = v;
          }
          monogatari.storage(s);
        },
    '식당 한쪽 구석에 가수 최유리가 홀로 앉아 있었다. 그녀의 얼굴에는 여전히 분노가 서려 있었다.',
    'char_protagonist 최유리 씨, 선장님과의 관계에 대해 들을 수 있을까요?',
    'char_suspect2 그 인간, 역겨웠어요. 계속 추근댔다고요. 그래서 증거라도 잡으려고 녹음기도 갖고 다녔어요. 이거요.',
    '그녀는 핸드백에서 작은 녹음기를 꺼내 보여주었다.',
    'char_suspect2 하지만 죽이진 않았어요. 그런 쓰레기 때문에 내 인생을 망칠 순 없으니까. 어젯밤엔 계속 방에서 노래 연습만 했어요.',
    '그녀의 증언은 선장에 대한 강한 살해 동기를 보여주었다.',
    'jump scene_investigation_hub_2',
  ],
  'scene_investigation_hub_2': [
    'show scene bg_dining_hall',
    '2차 수사를 시작한다. 남은 장소 중 어디를 조사할까?',
    {
      'Choice': {
        '[선장실] 조사': {
          'Condition': (function() { return monogatari.storage().vs_captain_room !== true; }),
          'Do': 'jump scene_investigate_captain_room_2'
        },
        '[기관실] 조사': {
          'Condition': (function() { return monogatari.storage().vs_engine_room !== true; }),
          'Do': 'jump scene_investigate_engine_room_2'
        },
        '[카지노] 조사': {
          'Condition': (function() { return monogatari.storage().vs_casino !== true; }),
          'Do': 'jump scene_investigate_casino_2'
        },
        '[갑판] 조사': {
          'Condition': (function() { return monogatari.storage().vs_deck !== true; }),
          'Do': 'jump scene_investigate_deck_2'
        },
        '[식당] 조사': {
          'Condition': (function() { return monogatari.storage().vs_dining_hall !== true; }),
          'Do': 'jump scene_investigate_dining_hall_2'
        }
      }
    },
  ],
  'scene_investigate_captain_room_2': [
    'show scene bg_captain_room',
    function() {
          const flags = JSON.parse('{\"vs_captain_room\":true}');
          const s = monogatari.storage();
          for (const [k, v] of Object.entries(flags)) {
            s[k] = v;
          }
          monogatari.storage(s);
        },
    '선장실을 다시 조사했다. 쓰레기통에서 찢어진 종이 조각을 발견했다. \'밀수... 약속한 금액을 당장...\'이라고 적혀있다.',
    '문 앞 카펫에서 희미한 기름 발자국을 발견했다. 기관실에서 사용하는 윤활유 성분 같다.',
    'jump scene_investigation_hub_3',
  ],
  'scene_investigate_engine_room_2': [
    'show scene bg_engine_room',
    function() {
          const flags = JSON.parse('{\"vs_engine_room\":true}');
          const s = monogatari.storage();
          for (const [k, v] of Object.entries(flags)) {
            s[k] = v;
          }
          monogatari.storage(s);
        },
    '기관실에서 윤서진 항해사를 만났다. 그녀는 22:30-23:30까지 설비 점검을 했다며 운행 일지를 보여주었다.',
    '일지를 살펴보니 23:00 기록의 잉크만 미세하게 달라 보인다. 나중에 급하게 쓴 것 같다.',
    'jump scene_investigation_hub_3',
  ],
  'scene_investigate_casino_2': [
    'show scene bg_casino',
    function() {
          const flags = JSON.parse('{\"vs_casino\":true}');
          const s = monogatari.storage();
          for (const [k, v] of Object.entries(flags)) {
            s[k] = v;
          }
          monogatari.storage(s);
        },
    '카지노에서 박선우를 만났다. 그는 어젯밤 계속 이곳에 있었다고 주장했고, 딜러 역시 그 사실을 증언했다.',
    'jump scene_investigation_hub_3',
  ],
  'scene_investigate_deck_2': [
    'show scene bg_deck',
    function() {
          const flags = JSON.parse('{\"vs_deck\":true}');
          const s = monogatari.storage();
          for (const [k, v] of Object.entries(flags)) {
            s[k] = v;
          }
          monogatari.storage(s);
        },
    '갑판에서 이정훈 씨를 만났다. 그는 어젯밤 23시 직전, 승무원 복장의 사람이 3층 복도 끝 \'창고 같은 문\'으로 사라지는 것을 봤다고 증언했다.',
    'jump scene_investigation_hub_3',
  ],
  'scene_investigate_dining_hall_2': [
    'show scene bg_dining_hall',
    function() {
          const flags = JSON.parse('{\"vs_dining_hall\":true}');
          const s = monogatari.storage();
          for (const [k, v] of Object.entries(flags)) {
            s[k] = v;
          }
          monogatari.storage(s);
        },
    '식당에서 최유리를 만났다. 그녀는 선장에게 성희롱을 당해왔으며, 증거를 잡기 위해 소형 녹음기를 가지고 다녔다고 털어놓았다.',
    '그녀의 핸드백에서 실제로 소형 녹음기를 확인했다.',
    'jump scene_investigation_hub_3',
  ],
  'scene_investigation_hub_3': [
    'show scene bg_dining_hall',
    '마지막 3차 수사를 시작한다. 어디로 갈까?',
    {
      'Choice': {
        '[선장실] 조사': {
          'Condition': (function() { return monogatari.storage().vs_captain_room !== true; }),
          'Do': 'jump scene_investigate_captain_room_3'
        },
        '[기관실] 조사': {
          'Condition': (function() { return monogatari.storage().vs_engine_room !== true; }),
          'Do': 'jump scene_investigate_engine_room_3'
        },
        '[카지노] 조사': {
          'Condition': (function() { return monogatari.storage().vs_casino !== true; }),
          'Do': 'jump scene_investigate_casino_3'
        },
        '[갑판] 조사': {
          'Condition': (function() { return monogatari.storage().vs_deck !== true; }),
          'Do': 'jump scene_investigate_deck_3'
        },
        '[식당] 조사': {
          'Condition': (function() { return monogatari.storage().vs_dining_hall !== true; }),
          'Do': 'jump scene_investigate_dining_hall_3'
        }
      }
    },
  ],
  'scene_investigate_captain_room_3': [
    'show scene bg_captain_room',
    function() {
          const flags = JSON.parse('{\"vs_captain_room\":true}');
          const s = monogatari.storage();
          for (const [k, v] of Object.entries(flags)) {
            s[k] = v;
          }
          monogatari.storage(s);
        },
    '선장실을 마지막으로 조사했다. 쓰레기통에서 \'밀수\'라고 적힌 협박 편지 초안을, 카펫에서 기름 발자국을 발견했다.',
    '...',
    'jump scene_investigation_end',
  ],
  'scene_investigate_engine_room_3': [
    'show scene bg_engine_room',
    function() {
          const flags = JSON.parse('{\"vs_engine_room\":true}');
          const s = monogatari.storage();
          for (const [k, v] of Object.entries(flags)) {
            s[k] = v;
          }
          monogatari.storage(s);
        },
    '기관실을 마지막으로 조사했다. 윤서진의 알리바이 증거인 운행 일지를 확보했다. 하지만 잉크가 미심쩍다.',
    '...',
    'jump scene_investigation_end',
  ],
  'scene_investigate_casino_3': [
    'show scene bg_casino',
    function() {
          const flags = JSON.parse('{\"vs_casino\":true}');
          const s = monogatari.storage();
          for (const [k, v] of Object.entries(flags)) {
            s[k] = v;
          }
          monogatari.storage(s);
        },
    '카지노를 마지막으로 조사했다. 박선우의 알리바이는 딜러에 의해 교차 검증되었다.',
    'jump scene_investigation_end',
  ],
  'scene_investigate_deck_3': [
    'show scene bg_deck',
    function() {
          const flags = JSON.parse('{\"vs_deck\":true}');
          const s = monogatari.storage();
          for (const [k, v] of Object.entries(flags)) {
            s[k] = v;
          }
          monogatari.storage(s);
        },
    '갑판을 마지막으로 조사했다. 이정훈 씨로부터 \'승무원 복장의 사람이 사라진 창고 같은 문\'에 대한 결정적인 목격담을 들었다.',
    'jump scene_investigation_end',
  ],
  'scene_investigate_dining_hall_3': [
    'show scene bg_dining_hall',
    function() {
          const flags = JSON.parse('{\"vs_dining_hall\":true}');
          const s = monogatari.storage();
          for (const [k, v] of Object.entries(flags)) {
            s[k] = v;
          }
          monogatari.storage(s);
        },
    '식당을 마지막으로 조사했다. 최유리로부터 선장의 성희롱에 대한 증언과 증거인 소형 녹음기를 확보했다.',
    '...',
    'jump scene_investigation_end',
  ],
  'scene_investigation_end': [
    'show scene bg_dining_hall',
    '모든 수사가 끝났다. 나는 생존자 전원을 라운지로 모이게 했다.',
    'char_protagonist 지금부터... 제가 알아낸 진실을 말씀드리겠습니다.',
    (function() {
          const result = (monogatari.storage().clue_count || 0) >= 5;
          if (result) {
            return '(단서는 충분히 모였다. 범인을 지목하고 트릭을 밝혀낼 수 있을 것 같다.)';
          } else {
            return '(단서가 부족한 것 같지만... 어떻게든 추리를 완성해야 한다.)';
          }
        }),
    'jump scene_deduction_start',
  ],
  'scene_deduction_start': [
    'show scene #2d2d44',
    '이제 범인을 지목할 시간이다...',
    'jump _deduction_q_culprit',
  ],
  '_deduction_q_culprit_wrong': [
    '아닙니다. 그 사람에겐 확실한 알리바이가 있거나, 결정적인 증거가 없습니다.',
    'jump _deduction_q_trick',
  ],
  '_deduction_q_culprit_correct': [
    '맞습니다. 범인은 바로 1등 항해사, 윤서진 씨입니다.',
    (function() {
          const s = monogatari.storage();
          s['correct_culprit'] = true;
          s['st_correct_culprit'] = true;
          monogatari.storage(s);
        }),
    'jump _deduction_q_trick',
  ],
  '_deduction_q_culprit': [
    '"강태준 선장을 살해한 범인은 누구입니까?"',
    {
      'Choice': {
        '박선우': {
          'Do': 'jump _deduction_q_culprit_wrong'
        },
        '최유리': {
          'Do': 'jump _deduction_q_culprit_wrong'
        },
        '윤서진': {
          'Do': 'jump _deduction_q_culprit_correct'
        }
      }
    },
  ],
  '_deduction_q_trick_wrong': [
    '아닙니다. 그것은 이 사건의 트릭이 아닙니다.',
    'jump _deduction_q_motive',
  ],
  '_deduction_q_trick_correct': [
    '정확합니다. 범인은 기관실의 소음을 방패 삼아 승무원 전용 통로로 이동해 범행을 저지르고, 돌아와 일지를 조작한 겁니다.',
    (function() {
          const s = monogatari.storage();
          s['correct_trick'] = true;
          s['st_correct_trick'] = true;
          monogatari.storage(s);
        }),
    'jump _deduction_q_motive',
  ],
  '_deduction_q_trick': [
    '"범인은 어떻게 완벽한 알리바이를 만들었습니까?"',
    {
      'Choice': {
        '카지노의 다른 손님을 매수하여 알리바이를 위증시켰다.': {
          'Do': 'jump _deduction_q_trick_wrong'
        },
        '미리 녹음해 둔 소리를 이용해 객실에 있는 척 위장했다.': {
          'Do': 'jump _deduction_q_trick_wrong'
        },
        '승무원 전용 통로로 이동 후, 기관실 일지를 조작했다.': {
          'Do': 'jump _deduction_q_trick_correct'
        }
      }
    },
  ],
  '_deduction_q_motive_wrong': [
    '그것은 다른 용의자의 동기일 뿐, 범인의 진짜 마음속 어둠은 아니었습니다.',
    'jump _deduction_complete',
  ],
  '_deduction_q_motive_correct': [
    '그렇습니다. 이 모든 비극은 과거 \'파랑새호\' 침몰 사건에서부터 시작된, 한 딸의 슬픈 복수극이었습니다.',
    (function() {
          const s = monogatari.storage();
          s['correct_motive'] = true;
          s['st_correct_motive'] = true;
          monogatari.storage(s);
        }),
    'jump _deduction_complete',
  ],
  '_deduction_q_motive': [
    '"그렇다면, 범인의 진짜 범행 동기는 무엇이었을까요?"',
    {
      'Choice': {
        '밀수 사실을 폭로하겠다는 선장의 협박 때문에.': {
          'Do': 'jump _deduction_q_motive_wrong'
        },
        '선장의 지속적인 성희롱을 참을 수 없어서.': {
          'Do': 'jump _deduction_q_motive_wrong'
        },
        '과거 선장의 보험사기로 희생된 아버지의 복수.': {
          'Do': 'jump _deduction_q_motive_correct'
        }
      }
    },
  ],
  '_deduction_complete': [
    '추리가 끝났다...',
    (function() {
    const s = monogatari.storage();
    
    if ((s.clue_count || 0) >= 5) {
      return 'jump scene_ending_true';
    }
    if (true) {
      return 'jump scene_ending_good';
    }
    if (true) {
      return 'jump scene_ending_normal';
    }
    if (true) {
      return 'jump scene_ending_bad';
    }
    return 'jump scene_ending_bad';
  }),
  ],
  'scene_ending_true': [
    'show scene #000000',
    '"폭풍 속의 진실"',
    'char_protagonist 당신은 과거 \'파랑새호\' 선장의 딸이군요. 강태준이 당신의 아버지를 파멸시키고, 어젯밤 그 사실을 모욕했기 때문에... 복수한 겁니다.',
    'char_culprit ...모든 걸 알고 있었군요. 네, 맞습니다. 아버님의 원수를... 갚았을 뿐입니다.',
    '나의 완벽한 추리 앞에, 윤서진은 모든 것을 자백했다. 그녀의 눈에서 뒤늦은 눈물이 흘러내렸다.',
    '태풍이 그치고 마침내 구조 신호가 연결되었을 때, 사건의 진실은 고요한 바다 위로 떠올랐다. 슬픈 복수극은 막을 내렸다.',
    'end',
  ],
  'scene_ending_good': [
    'show scene #000000',
    '"차가운 복수"',
    'char_protagonist 기관실 기름 발자국과 조작된 일지, 그리고 승무원 통로에 대한 목격 증언. 범인은 당신입니다, 윤서진 씨.',
    'char_culprit ......',
    'char_culprit 거기까지 밝혀내다니, 대단하군요. 네, 제가 죽였습니다.',
    '나의 논리적인 추궁에, 그녀는 범행을 인정했다. 하지만 끝내 자신의 진짜 동기에 대해서는 입을 다물었다.',
    '그녀의 마음속 깊은 어둠은 영원히 태평양의 심해에 잠기게 되었다.',
    'end',
  ],
  'scene_ending_normal': [
    'show scene #000000',
    '"우연한 해결"',
    'char_protagonist 선장실 근처에서 발견된 기관실의 기름 발자국... 윤서진 씨, 당신이 범인이라는 증거입니다.',
    'char_culprit ...그 발자국 하나로요?',
    'char_protagonist 다른 증거는... 아직 찾지 못했지만, 당신이 가장 유력합니다!',
    '결정적인 증거 하나로 범인을 지목하는 데는 성공했다. 하지만 범인이 어떻게 알리바이를 만들었는지, 왜 그랬는지는 명확히 설명하지 못했다.',
    '어딘가 찜찜함이 남는 반쪽짜리 해결이다.',
    'end',
  ],
  'scene_ending_bad': [
    'show scene #000000',
    '"뒤바뀐 운명"',
    'char_protagonist 범인은 바로 당신입니다, 박선우 씨! 선장의 협박 편지가 증거입니다!',
    'char_suspect1 뭐? 나는 계속 카지노에 있었다고! 말도 안 돼!',
    '나의 추리는 빗나갔다. 무고한 사람이 범인으로 지목되었고, 모두가 혼란에 빠졌다.',
    '그 혼란 속에서, 진범은 어둠 속에서 조용히 미소 짓고 있었다. 오리온호의 진실은 영원히 폭풍 속에 갇히고 말았다.',
    'end',
  ],
  'Start': [
    "play music main_bgm with loop",
    'jump scene_prologue_01',
  ]
});
