// 이 파일은 n8n 파이프라인에 의해 자동 생성됩니다.
// This file is auto-generated by the n8n pipeline.

const { Monogatari } = window;

// 캐릭터
Monogatari.characters({
  'sample': {
    name: '샘플',
    color: '#5bcaff'
  }
});

// 배경 (색상)
Monogatari.assets('scenes', {
  'bg_default': '#1a1a2e'
});

// 스크립트
Monogatari.script({
  'Start': [
    'show scene bg_default',
    '이것은 기본 템플릿입니다.',
    'sample 게임이 생성되면 이 내용이 교체됩니다.',
    {
      'Choice': {
        '확인': {
          'Text': '확인',
          'Do': 'end'
        }
      }
    }
  ]
});
