// 이 파일은 n8n 파이프라인에 의해 자동 생성됩니다.
// This file is auto-generated by the n8n pipeline.

const { monogatari } = window;

// 캐릭터 정의
monogatari.characters({
  'narrator': {
    name: '',
    color: '#ffffff'
  },
  'sample': {
    name: '샘플 캐릭터',
    color: '#5bcaff'
  }
});

// 배경 정의 (색상)
monogatari.assets('scenes', {
  'bg_default': '#1a1a2e'
});

// 스크립트
monogatari.script({
  'Start': [
    'show scene bg_default',
    '이것은 기본 템플릿입니다.',
    'sample 게임이 정상적으로 생성되면 이 내용이 교체됩니다.',
    {
      'Choice': {
        '시작하기': {
          'Text': '시작하기',
          'Do': 'end'
        }
      }
    }
  ]
});